### ISSUE TITLE
Use a single 'canonical' name

### ISSUE THREAD

**Issue by BibianaC** [ThreeSixtyGiving/grantvis#108]
https://github.com/ThreeSixtyGiving/insights-ng/pull/107#issuecomment-1039256666

The canonical name should be the same for Insights as for GrantNav.

**Comment by mariongalley** [comment]
@KDuerden Is there still an issue wrt Insights not using Canonical name for Funders?

**Comment by KDuerden** [comment]
Yes. It is specifically impacting the text in the header section - for example: [https://insights.threesixtygiving.org/?funders=GB-GOR-D5](https://insights.threesixtygiving.org/?funders=GB-GOR-D5)

The filter names in the table are using canonical name ok.

**Comment by mariongalley** [comment]
This issue is fixed in the new iteration of Insights PR #208
