### ISSUE TITLE
Sort order of chart values

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#109]
"Latest income of charity recipients" and "Age of recipient organisations" are sorting number alphabetically which is quite confusing. Please can they be sorted in the correct order based on the contents of the values?

![image](https://user-images.githubusercontent.com/82958988/154031832-5c54136c-602f-4a2f-aa3d-04e7a96b566e.png)

@michaelwood I'm not sure how complex this is to fix so I haven't tagged it prerequisite for live yet, but I think it would be preferable if it could be addressed today. Do you think that will be feasible?

**Comment by mariongalley** [comment]
Related to https://github.com/ThreeSixtyGiving/insights-ng/issues/30

**Comment by michaelwood** [comment]
Code around this is ~ https://github.com/ThreeSixtyGiving/insights-ng/blob/live/insights/static/js/data-display.js#L548 
Useful reference for sorting in js - https://javascript.info/array-methods#sort-fn

**Comment by michaelwood** [comment]
We found the culprit: converting the ordered dictionary from python into json in the template breaks the ordering https://github.com/ThreeSixtyGiving/insights-ng/blob/live/insights/templates/data-display.vue.j2#L15 

Somehow we need to safely pass the data from the python context into javascript without changing the order.

**Comment by mariongalley** [comment]
Just had a look in live and this is fixed!
