### ISSUE TITLE
Footer content to be updated

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#110]
Footer currently has placeholder copy

**Comment by mariongalley** [comment]
Some of it needs to be different from Live e.g. "Created by David Kane" is no longer accurate. Might need to give it some thought, but at least remove the placeholder copy and include the appropriate links.

I think it should be based on the GrantNav footer content but changing the bit about GrantNav to be about Insights.

**Comment by michaelwood** [comment]
@mariongalley

Change now deployed to http://insights.360dokku1.vs.mythic-beasts.com/
I made a bit of a combination of the GrantNav and current insights footer, I think it works, but let me know of any changes needed.

**Comment by mariongalley** [comment]
Looks great, thank you! A couple of points:
- About link is broken
- Can you change

> 360Insights is a free tool to help you understand funders better. You can combine and visualise 360Giving and charity data, and explore funding across different areas - from grant dates to types of recipients.

to

> 360Insights is a free tool to help you understand funding better. Combine and visualise 360Giving, charity and location data to see an overview of grants by amounts, dates, geography, types of recipients and funders.
