### ISSUE TITLE
Region chart available for selection on homepage but not displayed on results page

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantvis#117]
The region chart only appears on the homepage but not on the results page.

If a region has been select on the homepage the area shows on the map, but it isn't easy to see the number of grants in the region unless you click on the map, to get the tooltip.

The lack of region chart also means it isn't possible to select to view the results of more than one region, whereas the other levels to allow for multi-select.

I think the charts available on the results page should mirror those available on the results page to give users feedback on their selections and allow for more exploration by region.

**Comment by mariongalley** [comment]
Regions picker now available on results page

![image](https://user-images.githubusercontent.com/82958988/157031580-4a7e5392-3cbe-4c09-b70b-9ac4e25a3118.png)

Closing issue. Please re-open if this isn't done as expected.
