### ISSUE TITLE
See in GrantNav link on results page links to a blank search with LA filter

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantvis#119]
If I go to http://insights.360dokku1.vs.mythic-beasts.com/data?localAuthorities=E09000033 and click the "See in GrantNav" button, it links to `https://grantnav.threesixtygiving.org/search?` (ie, a blank GN search). 

It seems to be fine for a funder (e.g. the button on http://insights.360dokku1.vs.mythic-beasts.com/data?funders=GB-GOR-D5 links to `https://grantnav.threesixtygiving.org/search?fundingOrganization=GB-GOR-D5`. I've also checked funder types, countries and regions, so I think it is just LAs that it's a problem for.

**Comment by michaelwood** [comment]
Grantnav currently can't filter by `additional_data.locationLookup.ladcd` (local authorities) which is where insights gets it's LA data from. 

We will have to skip showing the link for this one for now, as we do with orgtype.

Needs adding to https://github.com/ThreeSixtyGiving/grantnav/blob/master/dataload/import_to_elasticsearch.py

**Comment by michaelwood** [comment]
Button is no longer being displayed for LA filters
