### ISSUE TITLE
Use a similar mechanism to GrantNav for triggering updates

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantvis#122]
GrantNav looks at the datastore to see when the latest data has been created. If it's newer than the data in grantnav it goes and fetches it. We could do with a similar mechanism in Insights if the expectation is that both tools will be in perfect sync. Relying on triggering this at a particular time of day isn't going to achieve this (same with covidtracker).

**Comment by robredpath** [comment]
>  if the expectation is that both tools will be in perfect sync. 

It might be helpful to think of this in terms of cycle length: how long should things be expected to be out of sync after a change happens? 

I don't think it's a requirement for that cycle to be 1 second. I think the cycle should be less than 24 hours. Somewhere in the middle is probably a good number, but we shouldn't spend too much time trying to make it go faster than we need it to!

What's the current cycle time for GrantNav/datastore?

**Comment by michaelwood** [comment]
> 
> What's the current cycle time for GrantNav/datastore?

GrantNav and the datastore are out of sync for between 44 minutes and 49 minutes depending on how the time of finish matches with the polling (every 5min). This out of sync time happens at 5am or whenever the datastore run is triggered manually.

**Comment by robredpath** [comment]
If we update the datastore during the day (for example, due to a takedown, or to correct some sort of failure) - is it still 44-49 minutes after the datastore updates that we'd see GrantNav update?

**Comment by michaelwood** [comment]
> If we update the datastore during the day (for example, due to a takedown, or to correct some sort of failure) - is it still 44-49 minutes after the datastore updates that we'd see GrantNav update?

Yep, GN takes 40 something minutes to download the data, load the elasticsearch index and then do the index swap.

**Comment by robredpath** [comment]
~~Can I infer from this that GN checks for updates every 10 minutes?~~

Just saw the answer above about polling every 5 mins

**Comment by KDuerden** [comment]
The goal for us is that if a funder publishes for the first time, we can share links to their data in all our tools at the same time, as soon as possible.

At the moment GrantNav shows their data from the next morning but Insights isn't ready until the following day - so we either hold back for a day or do two pieces of comms.

GrantNav & Insights wouldn't need to be in perfect sync, but the new data showing next day in both would be great situation to get to.

**Comment by mariongalley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Insights update to ensure yesterday's data available](https://trello.com/c/wEdbE1yo/252-insights-update-to-ensure-yesterdays-data-available)

**Comment by mariongalley** [comment]
https://opendataservices.plan.io/issues/32799#note-60

**Comment by michaelwood** [comment]
Something also to consider when developing this is seeing if we can get a speed increase. The current full load takes approx 1h30m to load in 10k batches. I would imagine loading a package of json data should be quicker.

**Comment by mariongalley** [comment]
@michaelwood FYI we had a new publisher yesterday whose data appears in GrantNav and the Quality Dashboard but not Insights. I assume that's because of this known issue?

**Comment by michaelwood** [comment]
Yes that is likely to be the case. Should see it in insights tomorrow.

**Comment by mariongalley** [comment]
It looks to us like data added yesterday is now in Insights - this could be because of the performance improvements to the datagetter impacting Insights' update speed. Is this it possible that this issue is resolved permanently? @michaelwood

**Comment by michaelwood** [comment]
Yes! you're right that the performance improvements in the datagetter will have allowed this to happen. Interesting..!

I think it is worth fixing properly because, it would be better if we can make insights reactive to the data pipeline rather than relying on timing. At the moment there is a potential issue if insights grabs the data _while_ the data processing is in progress. There is also the case when more data is added on a particular day it won't align or if we need to re-run the data pipeline it also won't trigger an update.
