### ISSUE TITLE
Include homepage link to view Insights view of COVID-19 response grants

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantvis#125]
We want to be able to eventually retire the standard alone [Covid grants tracker](https://covidtracker.threesixtygiving.org/), and instead have the grants displayed in an Insights view.

**Comment by mariongalley** [comment]
Short term fix is "content cards" on Insights homepage that link out to the Covid Tracker and other Dashboards.

Long term fix could carrying across the functionality of Covid Tracker into Insights so we can retire it as a separate tool.

**Comment by mariongalley** [comment]
This is now done thanks to the ~ new insights homepage ~
