### ISSUE TITLE
Set up Insights helpsite similar to GrantNav helpsite

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#127]
This should explain:

- How we use Recipient & Beneficiary locations
- Why we don't do the Heatmap by amounts rather than number of grants
- Explain terminology
- Explain how to multiselect areas (and that you can only pick one via the heatmap)

**Comment by mariongalley** [comment]
Also explain #64

**Comment by robredpath** [comment]
Superceded by data use guidance
