### ISSUE TITLE
Create management mechanism for uploaded files

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantvis#13]
Create a flask command to manage uploaded data

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create management mechanism for uploaded files](https://trello.com/c/JwEj4i4L/21-create-management-mechanism-for-uploaded-files)

**Comment by michaelwood** [comment]
Out of scope for Q1 2022
