### ISSUE TITLE
Add site metadata to base template for SEO/Social media stuff

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantvis#135]
Create some copy for the description / tags in Insights

e.g. in GrantNav we have 

```html
<meta property="og:title" content="360Giving GrantNav">
<meta property="og:description" content="Search, explore and download UK grants data published by funders in the 360Giving Data Standard">
<meta name="description" content="Search, explore and download UK grants data published by funders in the 360Giving Data Standard">

```

**Comment by mariongalley** [comment]
Text should say: 360Insights is a free tool to help you understand funders better. You can combine and visualise 360Giving and charity data, and explore funding across different areas - from grant dates to types of recipients.
