### ISSUE TITLE
Include number of funders in search in top results

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantvis#144]
The filters results from 360Insights do not include the number of funders included in the search results in the tool.

This is an important piece of information so it should be prominently displayed. This could replace Average Grant figure as the fourth box in the top results.

For example for this filtered result: https://insights.threesixtygiving.org/data?funderTypes=Local%20Government
Instead of this:

![image](https://user-images.githubusercontent.com/20462640/165699225-8619eef6-6b8d-4348-83c4-7174d86449fb.png)

The top display would be this (order of boxes to be agreed):

![image](https://user-images.githubusercontent.com/20462640/165699456-7e31e397-81f1-4315-81d7-1327ff6407b0.png)

The average grant size figure is less useful than number of funders. We have had feedback from funders that mean average grant is not helpful and for funder with a range of programmes and grant sizes, this figure is misleading to prospective applicants.

The Award Amount chart provides more useful and accurate information about grant sizes

![image](https://user-images.githubusercontent.com/20462640/165699644-15403ada-2940-4f5b-867c-8f3725f0632e.png)

**Comment by BibianaC** [comment]
@KDuerden This change would only apply to the filter results page, not to the homepage, right? Would you want the order as it is? what about the colour, is yellow ok?

**Comment by KDuerden** [comment]
I do mean in the homepage as well as the filtered results. The number of funders that shows at the bottom on the funder filter list isn't that prominent so would be easy to miss - I think having it appear as part of the key stats is helpful.

I think it should be right-hand box, instead of Average. It can stay yellow.

**Comment by BibianaC** [comment]
Thanks @KDuerden

**Comment by KDuerden** [comment]
@BibianaC and @michaelwood is there an update on this development, and eta for this going live? Thank you!

**Comment by Lathrisk** [comment]
@KDuerden @mariongalley 

This work is currently in review, and should be deployed soon. I've attached a couple screenshots to show the current appearance on the homepage and a filtered set.

Are you happy for us to proceed with the deployment?

![funders-update-data](https://user-images.githubusercontent.com/517804/179988207-6dcbe874-a88f-4418-b7cd-8f1b6d26fc7a.png)
![funder-update](https://user-images.githubusercontent.com/517804/179988211-ef3764b9-3558-46ba-816f-f45e46596064.png)

**Comment by mariongalley** [comment]
This looks good to me, thank you!

**Comment by michaelwood** [comment]
This is merged and deployed. I have spotted a minor issue that we get on the data page (not home page) that the number displays as NaN as it doesn't have an initial value while it is loading. I missed this in review but it's a tiny fix so will just push & deploy that now.

**Comment by mariongalley** [comment]
Thanks @michaelwood, looks good to me!
