### ISSUE TITLE
Add a tooltip to interactive chart bars / labels 

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantvis#150]
Although we hint to the user that certain chart bars labels are clickable we don't give reassurance as to what they do. We could do this with some copy in a section at the top of page and a tooltip on the chart bars / labels themselves.

**Comment by mariongalley** [comment]
### Suggested copy:

- Top of the page (below headline stats and above Funders chart): "Click on any chart to filter your selection."
- Below Funders chart: "Click on the bars or labels to select one or more funders."
- Below Funding org type chart: "Click on the bars or labels to select one or more funding organisation types."
- Below Countries chart: "Click on the bars or labels to select one or more countries." 
- Below Regions chart: "Click on the bars or labels to select one or more regions."
- Below LAs chart: "Click on the bars or labels to select one or more local authorities."
- Below map, replace: "Click on an area to view number of grants. // Zoom into a Country/Region to view Local Authority-level data." with: "Zoom into a Country/Region to view Local Authority-level data. // Click on an area to view number of grants, and click on the number of grants to select the area."
- Below Award Amount chart: "Click on the bars or labels to select one or more award amount ranges, or enter a custom range."
- Below Award Date chart: "Enter a date range to filter your selection."
    - Am I right in thinking clicking on the bars doesn't do anything?
- Below Programmes chart: "Click on the bars or labels to select one or more grant programmes."
- Am I right in thinking you can't filter by source of location info?
- Below Recipient types chart: "Click on the bars or labels to select one or more recipient types."
- Below Income of charity recipients chart: "Click on the bars or labels to select one or more ranges of latest incomes of charity recipients."
- Below Age of organisations chart: "Click on the bars or labels to select one or more age ranges of recipients."

**Comment by mariongalley** [comment]
@michaelwood Do you think this should be a tooltip rather than copy at the bottom of each chart where e.g. the map instructions are?

**Comment by codemacabre** [comment]
I'm picking this up, @mariongalley. In response to your questions:

> Am I right in thinking clicking on the bars doesn't do anything?

Correct, the filter is only applied when entering a date range. I imagine this is because the click target is a bit too small to use the bars interactively, plus the bars only allow individual months to be selected, not a range.

> Am I right in thinking you can't filter by source of location info?

Correct, although I'm not sure why. @michaelwood is this intentional?

> Do you think this should be a tooltip rather than copy at the bottom of each chart where e.g. the map instructions are?

Essential information unavailable elsewhere generally shouldn't be hidden behind tooltips, as they're inherently inaccessible. Putting this information as copy below each chart makes it much more user-friendly.
