### ISSUE TITLE
Show up to five funders names in top display

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantvis#153]
I think 3 is too few, and we have an example of a user who needs to be able to display 5 funders together so can we explore whether this is technically feasible, and can work within the current constraints of the design system.

There are a few related issues, in terms of how Insights displays the funder names and count.

Closed issue about the [header/title](: https://github.com/ThreeSixtyGiving/insights-ng/issues/21
), although the current behaviour doesn't actually include the number of publishers when it exceeds current maximum of three names.

However I've raised another issue that requests the [funder count to feature in the top result boxes](https://github.com/ThreeSixtyGiving/insights-ng/issues/144) - which I think is a better solution than including this in the title

There is also the wider issue of how [funder names show in the list](https://github.com/ThreeSixtyGiving/insights-ng/issues/59) are when lots of funders are filtered, so more broadly I think there is room for improvement in how Insights displays titles/names issues that we may need to tackle more holistically.

**Comment by michaelwood** [comment]
e.g. https://insights.threesixtygiving.org/data?funders=US-EIN-39-1916960&funders=GB-CHC-1035628&funders=GB-LAE-GLA&funders=GB-CHC-1066739&funders=GB-CHC-1119845

**Comment by KDuerden** [comment]
Yes, exactly.

This would also be a good filter to test with. 

5 separate trusts published by the same organisation, and some of the names are a bit longer than average: https://insights.threesixtygiving.org/data?funders=GB-CHC-326340&funders=GB-CHC-1091658&funders=GB-CHC-312749&funders=GB-CHC-210291&funders=GB-CHC-1087167

**Comment by Lathrisk** [comment]
@KDuerden @mariongalley 
I've attached a screenshot for the example above that includes 5 funders. Even with these long titles it doesn't take up significantly more space, but more funders might slowly erode readability. 

![funders-5](https://user-images.githubusercontent.com/517804/181036768-45dd234f-6242-4f04-ab88-569066399080.png)

**Comment by mariongalley** [comment]
Thanks @Lathrisk , this looks good to me. I agree any more would be quite hard to read.

With Katherine's blessing I'd be happy for this to go live.

**Comment by KDuerden** [comment]
Thanks @Lathrisk @mariongalley - I think that looks good, especially given the space constraints on this header design.

**Comment by Lathrisk** [comment]
@KDuerden @mariongalley This has now been deployed.
