### ISSUE TITLE
Footer links & Policies

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#157]
1. Update About link to https://insights.threesixtygiving.org/about
2. Update copy on About page - doc to be created

**Comment by codemacabre** [comment]
> 2. Update copy on About page - doc to be created

@mariongalley Has the doc been created for this to be completed?

**Comment by mariongalley** [comment]
@codemacabre Oops sorry! [Here it is](https://docs.google.com/document/d/1piHhgxvj8PXrDV_nC2pk5h4XwRZxvSkBw1UGfAM1Gro/edit#heading=h.ongjpv11xwt3)

**Comment by mariongalley** [comment]
@codemacabre Could you or someone at ODSC team fact-check it as well please?

**Comment by codemacabre** [comment]
@mariongalley Thank you. I've made a couple of minor edits but otherwise looks good.

**Comment by mariongalley** [comment]
Thanks @codemacabre - when will I be able to test this in live?

**Comment by codemacabre** [comment]
@mariongalley Should be there now.
