### ISSUE TITLE
Remove All Grants in the Funding Organisation types chart & show all charts in empty searches/homepage

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#158]
Selecting All Grants in the Funding Organisation types chart does not load the results page successfully
https://insights.threesixtygiving.org/data?funderTypes=all

**Comment by mariongalley** [comment]
Agreed we don't need an All Grants bar on the Funding Org Type filter (we don't one anywhere else and it's a circuitous route to an empty search).

Suggest instead of supporting an empty search we add the charts that are available on the Results page but not the Homepage to the Homepage. This would be a new feature.

**Comment by mariongalley** [comment]
@michaelwood Is it possible to also investigate how and when the All Grants appeared in the Funding Org Type filter and whether we can introduce some monitoring or similar to identify when the values in the filters change? I understand they're driven by the data so it would be good to keep an eye on any unexpected changes.

**Comment by michaelwood** [comment]
Change deployed

**Comment by mariongalley** [comment]
Thanks @michaelwood & @codemacabre 

> Suggest instead of supporting an empty search we add the charts that are available on the Results page but not the Homepage to the Homepage. This would be a new feature.

Would you like me to raise this as a separate issue, or are you happy to tackle this next?
