### ISSUE TITLE
Stop deriving Recipient address data in Insights

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#159]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

Deriving Recipient address data is a problem for a few reasons:

- It takes away control from publishers by guessing at things that they haven't explicitly said in their data
- It assumes that the location of the recipient org is relevant to the grant, when the publisher may have intentiionally left it out because it's not relevant.
- It disincentivises publishers for whom location is relevant from providing geolocation data, because their data still appears on the Insights map even if they didn't share a location.
- Even if we are completely transparent about how we derive the location of the Recipient org by matching the data to other datasets, if users don't understand it fully, they can't make an informed decision about the quality/meaningfulness of that data.

**Describe the solution you'd like**

Stop deriving Recipient address data in Insights (but keep it in GrantNav download)

**Describe alternatives you've considered**

We considered giving users control about whether to include the derived Recipient location on the Insights map - however we believe this wouldn't be used much as it's very difficult to explain/understand.

**Additional context**

**Comment by drkane** [comment]
Related to https://github.com/ThreeSixtyGiving/datastore/issues/82

**Comment by mariongalley** [comment]
- Agreed that 'deriving Recipient address' means when there is no Recipient address in the data and we used the org ID to get the address from the charity commission
- Confirmed that we are still happy to derive geodata when for e.g. a postcode was shared and we fetch the associated district, region etc
- Noted that currently we can't tell these 2 things apart as they both appear in the datastore in the same way

2 options:
- Stop converting postcodes of recipients fetched from FTC into geodata
- Store this in a different way and label it clearly

**Comment by michaelwood** [comment]
This should be fixed now, we no longer use the looked up geo data to indicate the impact location of the grant
