### ISSUE TITLE
Insights Map should be hidden when there are no grants to show

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#162]
Not sure if this is also an issue in Live, but I came across it when testing the removal of derived Recipient Location in Insights.

For example Youth Music has [derived locations in Live Insights](https://insights.threesixtygiving.org/data?funders=GB-CHC-1075032) but [no usable Location data in Dev Insights](http://insights-test.360dokku1.vs.mythic-beasts.com/data?funders=GB-CHC-1075032).

The map still appears, only blank - instead it should be hidden like the other geo charts are.

**Comment by mariongalley** [comment]
Same issue for Grocers' charity: [Live](https://insights.threesixtygiving.org/data?funders=GB-CHC-255230) / [Dev](http://insights-test.360dokku1.vs.mythic-beasts.com/data?funders=GB-CHC-255230)

**Comment by michaelwood** [comment]
The map's api authorisation token on dev isn't installed so maps won't display

**Comment by mariongalley** [comment]
Oh right so it never displays on Dev - that's good to know. What about the other geo charts?

**Comment by michaelwood** [comment]
I've nicked the API auth token from the live site so the map should display now, sorry about that. 

From what I can tell the geo charts are not displayed for those funders because there is no geo data in their grants and it was previously using the FTC postcode data. I've verified this by checking in grantnav (dev and live), but would be good to have another pair of eyes on that.

**Comment by michaelwood** [comment]
And looking at [Youth Music 's data](https://network.youthmusic.org.uk/sites/default/files/360G-YouthMusic-Export.xlsx) they only supply a recipient org-id and no other info so we don't have any geo data there.

**Comment by mariongalley** [comment]
OK, so in that case this bug is legitimate in that if there's no geodata and the geocharts are hidden then the map should be too

**Comment by mariongalley** [comment]
Update: The map looked bad because it wasn't working but the empty state of the map looks fine actually, so it's not essential to hide the map when there's no location data. Closing issue.
