### ISSUE TITLE
Name of map is showing code instead of user friendly header

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#172]
Insights map display name is showing some code:

![image](https://user-images.githubusercontent.com/82958988/216936773-9fa329cd-6763-47ae-b390-09ffe143b127.png)

Please can you reinstate the user friendly header?

**Comment by codemacabre** [comment]
Whoops, I'm on it.

**Comment by michaelwood** [comment]
Ah looks like a missing colon on homepage.vue.j2 line 137
