### ISSUE TITLE
Adding recipient type filter/graph to Insights

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantvis#182]
> Add Recipient chart for selecting Org vs Ind vs both - separate chart from existing Recipient Type chart

**Comment by michaelwood** [comment]
@mariongalley @KDuerden Should the existing Recipient type graph be renamed? - e.g. Recipient organisation type?

**Comment by mariongalley** [comment]
@michaelwood Yes please

**Comment by mariongalley** [comment]
This is done
