### ISSUE TITLE
Award Amount graph axes inconsistent with GrantNav

### ISSUE THREAD

**Issue by anambcodes** [ThreeSixtyGiving/grantvis#185]
**Describe the bug**
The GrantNav Summary graph has the range 1k to 5k, whereas Insights has 1001 to 2k and 2001 to 5k 

**To Reproduce**
Steps to reproduce the behaviour:
1. View the GrantNav summary graph
2. View the Insights Award Amount Graph

Expected behaviour
Consistent axes - Insights should match GrantNav, i.e. have a 1k to 5k range only.

Screenshots
![image](https://user-images.githubusercontent.com/128042420/229178441-f2767834-4275-4574-93ce-45fe6103741c.png)

![image](https://user-images.githubusercontent.com/128042420/229178129-115771f6-cb36-4b1c-9841-05520e0ee941.png)

**Comment by michaelwood** [comment]
Thanks for reporting this issue Anam. I agree it would be an improvement if they matched. (I've re-tagged this as an enhancement as we use the "bug" tag generally to indicate that something is malfunctioning/not working as designed).

**Comment by mariongalley** [comment]
This issue is fixed in the new iteration of Insights PR #208
