### ISSUE TITLE
Award date graph to only show 19 or 20 most recent years

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#187]
Presence of very old data makes the Award Date graph less useful and harder to read. Show only the past 10 years instead:

![image](https://user-images.githubusercontent.com/82958988/229851908-f2b24b4a-5cf9-4d90-b03c-d8973071f9d3.png)

Note: this shouldn't update the selection for the rest of the charts or prevent selecting older ranges in the filter.

Copy will be needed to explain the chart only shows the past 10 years.

**Comment by mariongalley** [comment]
Alternative proposal is to just pre-populate the filter with an earliest date 20 years ago (we could do this in both GrantNav and Insights for them to match). I think we need to think about this a bit more before we go ahead.

It would also be good to exclude very old data from the Quality Dashboard.

**Comment by mariongalley** [comment]
Confirmed ideal solution would be to have a "Older" bar like on GrantNav

![image](https://user-images.githubusercontent.com/82958988/236508162-60b58508-0f7b-48b3-b207-634043f1d427.png)

**Comment by codemacabre** [comment]
@mariongalley Just wanted to check in about this. Setting the amount of visible data to the last 20 years is fairly straightforward, but I'm currently working on trying to get an 'Older' bar without losing the nice formatting of the $x$ axis. Doing so has introduced some axis-related bugs, so I was wondering if you'd be happy with just trimming off the outlier data instead? Adding an 'Older' bar without axis issues might involve rewriting the chart considerably.

**Comment by mariongalley** [comment]
Thanks for looking into this @codemacabre, I think for transparency I'd much prefer to show what we've done with the older data, but it depends how much work rewriting the chart involves as I can imagine it might not be proportionate.

**Comment by codemacabre** [comment]
@mariongalley Before creating a PR, I wanted to check you're happy with my current implementation. It now,
+ Shows an 'Older' bar when there isn't a min date specified
+ Shows individual older dates when a min date is specified (back to 1991)

Some idiosyncrasies:
+ The page reloads when dates are filtered (rather than just the chart updating) -- there was an existing bug with labels which was accentuated with this new implementation that's fixed by reloading the page, so it does this automatically now
+ $x$ axis labels are no longer handled automatically to allow for the 'Older' label, but this only works by customising them to always show month and year and letting the chart control the number of labels. This results in the $x$ axis appearing a little busier than previously:

![image](https://github.com/ThreeSixtyGiving/360insights/assets/49149591/ee7a2570-e730-4902-85e7-76ea6528a4f7)

**Comment by mariongalley** [comment]
@codemacabre Thanks for this

> x axis labels are no longer handled automatically to allow for the 'Older' label, but this only works by customising them to always show month and year and letting the chart control the number of labels

I'm struggling to get live Insights to load when filtering by date. Could you tell me what the logic is currently for when they show month and when they don't? My intuition is that it would be better to never show month in the labels than to have it be really busy most of the time.

**Comment by codemacabre** [comment]
> I'm struggling to get live Insights to load when filtering by date.

This is something I've noticed on the live site too, intermittently. Not sure why.

> Could you tell me what the logic is currently for when they show month and when they don't? My intuition is that it would be better to never show month in the labels than to have it be really busy most of the time.

The original logic was to only show months when the date range was a year or less, but there's a problem displaying just-year labels I haven't been able to resolve yet. It's possible there's an issue with the version of chartjs we're using (we're using 2.9.4, current version is 4.3.0) but I'll need to investigate further.

**Comment by mariongalley** [comment]
Thanks @codemacabre, ideally we'd be able to resolve the x axis issue so that we can control when to show months or not, as I think the screenshot above is too busy

**Comment by mariongalley** [comment]
I think this closes #72 , although date filter currently won't load in live

**Comment by mariongalley** [comment]
This could fix #51 as well
