### ISSUE TITLE
Update copy on Recipient org type chart for individuals

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#190]
Instead of: "X values are not found."

Say: "Recipient organisation type was not available for X grants because they were to individuals"

**Comment by mariongalley** [comment]
@michaelwood FYI

**Comment by codemacabre** [comment]
@mariongalley Do you want similar updates to the copy on **Type of grant recipient** and **Type of grant** charts, as they also have the phrase "X values are not found."?

**Comment by mariongalley** [comment]
@codemacabre I can't see any 'values are not found' copy on the **Type of grant recipient** or the **Type of grant** charts, can you send a screenshot or link of where you're seeing that?

![image](https://github.com/ThreeSixtyGiving/360insights/assets/82958988/858d91ad-1f1e-4b77-a5fa-8f1411a800db)

![image](https://github.com/ThreeSixtyGiving/360insights/assets/82958988/6d70c014-9b44-49a9-87cd-649f7bd01656)

**Comment by codemacabre** [comment]
It's in the code and displays while the data is loading (which is usually only for a brief moment):
![Screenshot 2023-06-06 at 12-46-28 360Giving Insights](https://github.com/ThreeSixtyGiving/360insights/assets/49149591/de3a7d2a-979d-452d-88f2-955e2133f238)
![Screenshot 2023-06-06 at 12-46-43 360Giving Insights](https://github.com/ThreeSixtyGiving/360insights/assets/49149591/eb045af2-4c80-4345-bfaf-fed84e8caec9)

**Comment by mariongalley** [comment]
Oh yeah, thanks! What do the other charts say while they're loading @codemacabre ?

**Comment by codemacabre** [comment]
@mariongalley The only others that say anything similar are:

Distribution of Grants by location:
> 0 grants did not have location data available.

Latest income of charity recipients:
> Latest income is not available for 0 grants.

Age of recipient organisations:
> Organisation age is not available for 0 grants.

The remaining locational charts don't display at all while the data is loading, and the Award Amount chart only shows the chart description beneath a blank chart.

Should I hide all charts until the data is loaded? That makes for a much cleaner and consistent page.

**Comment by mariongalley** [comment]
> Should I hide all charts until the data is loaded? That makes for a much cleaner and consistent page.

Yes that sounds good @codemacabre
