### ISSUE TITLE
10,000 record limit to open in Insights to be removed in GrantNav

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#209]
Limit of 10,000 records need no longer apply so please remove from Insights Voyager

**Comment by michaelwood** [comment]
Note for self: Fixed in version of this commit https://github.com/ThreeSixtyGiving/grantnav/commit/62a687a0613c5c85c14d000cb4575c850a857599

**Comment by mariongalley** [comment]
Confirmed & tested

**Comment by michaelwood** [comment]
I've made a note in my go-live check-list to make sure these point to the correct servers, so will close this issue for now
