### ISSUE TITLE
Data page title and subtitle

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantvis#21]
The data page's title is currently always defaulting to "360Giving publishers between 2013 and 2021" 

This is a property of the data page vuejs app that is available in the templates as {{title}} and {{subtitle}} . It would be good to restore the behaviour of showing the most relevant title. e.g. if filtered by particular funder put the funder name in the title

**Comment by KDuerden** [comment]
Fixing this issue would mitigate this issue I've raised #59
Especially for single funders wanting to view just their data, which is the way users have been used to seeing their data (in current Insights) so it would be good to retain this feature if possible.

**Comment by michaelwood** [comment]
When only 1 to 3 funders are selected as filter make sure this is displayed in the title. More than this adds the count of funders selected

**Comment by michaelwood** [comment]
I think we have some further tweaking in this area but with https://github.com/ThreeSixtyGiving/insights-ng/commit/0b6c92efadf5c40693a7a4e57677c1d190b304f9 I think we can closing this issue
