### ISSUE TITLE
Funder name(s) not displaying in kicker when 1-5 funders are selected

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#212]
Live Insights displays the name(s) of the funder(s) selected when 1-5 funders are selected but new Insights doesn't.

This is important because funders link to link to the Insights view filtered to show their grants from their websites, and it's important that people can see at a glance that it's their Insights page.

New Insights screenshot:

![image](https://github.com/ThreeSixtyGiving/360insights/assets/82958988/e75f944c-7cfe-451d-b101-cb8a06679b8c)

Old Insights, 1 funder:

![image](https://github.com/ThreeSixtyGiving/360insights/assets/82958988/39015f2e-495b-4fb0-a41e-a1f2c633976b)

Old Insights 5 funders:

![image](https://github.com/ThreeSixtyGiving/360insights/assets/82958988/b3b0074d-3744-4e62-8574-a8716f1817da)

New Insights > 5 funders:

![image](https://github.com/ThreeSixtyGiving/360insights/assets/82958988/2ab1d315-6b19-46a3-b2f8-3d2ac732febc)

**Comment by michaelwood** [comment]
I've implemented this and you can test it on dev server, I didn't limit it to showing just the first 5 funder names, as I think it would be an improvement to just show all, even if this section does get larger - it's a bit mysterious for the user if it "randomly" stops showing funder names.

**Comment by mariongalley** [comment]
Great, thanks! Have tested and happy to close this
