### ISSUE TITLE
Kicker shows start date after end date if only a start date is selected

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#213]
Insights voyager kicker shows the start date after the end date if only a start date is selected

![image](https://github.com/ThreeSixtyGiving/360insights/assets/82958988/8927b7ea-e64b-4248-99da-ae6808a5aa29)

**Comment by michaelwood** [comment]
Fixed push to dev

**Comment by mariongalley** [comment]
Tested and confirmed fixed
