### ISSUE TITLE
Award amount chart - bar labelling doesn't match behaviour

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#215]
If I set the amount to be max £10k, the £10,001-50,000 bar has data in it, presumably because it now includes grants worth exactly £10k whereas it previously didn't. This is good as it aligns with the GrantNav filters (and fixes #185), so I think it's just a case of renaming the axis labels.

Not sure whether it's better to switch them to be £1,000-£4,999 ; £5,000-£9,999 ; £10,000-£49,999 or to keep it like GrantNav i.e. £1,000-£5,000 ; £5,000-10,000 ; £10,000-£50,000 and keep some ambiguity

![image](https://github.com/ThreeSixtyGiving/360insights/assets/82958988/c6e54469-d149-4905-bbe9-5213e9ff66ed)

**Comment by mariongalley** [comment]
Agreed with Katherine it's better to match Insights and do rounding rather than switch labels to e.g. £1,000-£4,999

**Comment by michaelwood** [comment]
> Agreed with Katherine it's better to match Insights and do rounding rather than switch labels to e.g. £1,000-£4,999

Is that match live insights or a typo and meant to be match GrantNav?

**Comment by mariongalley** [comment]
@michaelwood match live insights please!

**Comment by michaelwood** [comment]
Fixed pushed to dev

**Comment by mariongalley** [comment]
Tested and confirmed fixed
