### ISSUE TITLE
Age & Income of Recipients charts should be side by side

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#220]
Live

![image](https://github.com/ThreeSixtyGiving/360insights/assets/82958988/3e12c267-047b-4cc6-ba67-9248f7b363ba)

Dev

![image](https://github.com/ThreeSixtyGiving/360insights/assets/82958988/2400e02d-02de-4c25-913c-07f9a82345b7)

**Comment by michaelwood** [comment]
Now fixed in dev

**Comment by mariongalley** [comment]
Confirmed tested
