### ISSUE TITLE
Funder name filters don't work for funders where the canonical ID is different from what they use in their data

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantvis#223]
This issue also exists in GrantNav, and was reported in Planio issue [41978](https://opendataservices.plan.io/issues/41978#note-8)

When a funder name is selected, the canonical ID forms the URL but the results are blank.
![image](https://github.com/ThreeSixtyGiving/360insights/assets/20462640/ba785ed8-6d81-441c-b46d-d227e5ad712b)

If you manually change the org ID to the one used by the funder in it's data, the data shows as expected, but there is no way to select their data directly through the filters.

**Comment by mariongalley** [comment]
@michaelwood Would this be fixed by us updating the Org IDs in Salesforce? If so, we'd be happy to do that as a short term fix.

This isn't a prerequisite for live but we do need a long term solution and probably to communicate about it if it persists much longer.

**Comment by michaelwood** [comment]
Fixed & deployed in dev
