### ISSUE TITLE
Funders chart has a double scroll bar when many funders are selected

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#224]
When multiple funders (14) selected, the funders chart splits into two sections, with vertical scroll bars. These clip against each other so the full list of selected funders is covered over by the start of the list of funders you can select. This is visually confusing/messy.

![image](https://github.com/ThreeSixtyGiving/360insights/assets/82958988/6309cc3f-96f2-4b8f-8d69-cac7c8134172)

**Comment by michaelwood** [comment]
Fixed and deployed to dev
