### ISSUE TITLE
Change copy from “Recipient individuals” to “Grant to individuals”

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#228]
Change copy from “Recipient individuals” to “Grant to individuals” in the headline stats

**Comment by michaelwood** [comment]
I think the grammar on this could be improved however this is now updated & deployed.

**Comment by mariongalley** [comment]
@michaelwood What do you propose, "Grants to Individuals" or something else?

**Comment by michaelwood** [comment]
* Individual Recipients
* Received by Individuals (then the orgs one could be Received by Organisations) 
* Recipient Individuals (GrantNav, DQT, Quality Dashboard)

**Comment by mariongalley** [comment]
@michaelwood I like Received by Individuals, as the other two don't solve the problem Tania's raised of the individual IDs not being 1:1 with real individual people. Let me get back to you to confirm

**Comment by mariongalley** [comment]
We won't change it to Received by Individuals, but could you change it to plural "Grants to Individuals" as the count shows many @michaelwood ? Does this have any impact on GrantNav?

**Comment by michaelwood** [comment]
> Does this have any impact on GrantNav?

No effect on GrantNav, this one is copy in the Insights templates.
