### ISSUE TITLE
Update 360Insights to GrantVis

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#242]
Please can you

1. Update the GrantVis application's logo to the attached

2. Replace references to 360Insights with GrantVis in the footer, git repo, and About 360Insights page.

3. For the Nav, could we keep the 360Insights item and link it to the new insights homepage at https://insights.threesixtygiving.org/ but also have a GrantVis item?

![Image](https://github.com/user-attachments/assets/14e2bc0d-5d5f-460d-9918-0f7bd2e1ebf6)

**Comment by michaelwood** [comment]
Have you got the image as an SVG? - would be best if we could just do a drop in/scaleable replacement if possible.

(current - https://github.com/ThreeSixtyGiving/360insights/blob/live/insights/static/images/360insights-color.svg )

**Comment by mariongalley** [comment]
Is this OK @michaelwood?

 [![GrantVis](https://github.com/user-attachments/assets/d336e0a3-7d1d-4a66-a681-929ae7ee8a58)
](url)
