### ISSUE TITLE
Award amount graph ordering 

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantvis#30]
The award amount graph order has gone, neither label or amount is ordered.

**Comment by mariongalley** [comment]
+1 was about to raise this but saw it's already here. Screenshot if that's helpful:
![image](https://user-images.githubusercontent.com/82958988/151334559-51b7472e-5c66-43eb-a536-a9ed1675844a.png)

**Comment by michaelwood** [comment]
hint: Looks like alphabetical sorting

**Comment by mariongalley** [comment]
@michaelwood am I right in thinking this was fixed at the same time as #109 ?

Looks resolved in live here:
![image](https://user-images.githubusercontent.com/82958988/170285281-e7bfb85f-b0f2-4b20-8363-8ccc4f9a888a.png)

**Comment by BibianaC** [comment]
Yes, @mariongalley. It was the same fix.

**Comment by mariongalley** [comment]
@BibianaC Question from Katherine - would it be possible to stop £5,001-£10,000 from wrapping? I've tested on a bunch of screen sizes and it does it in all cases.

**Comment by BibianaC** [comment]
@mariongalley We will look into this. I have opened a new issue. #149
