### ISSUE TITLE
Printable: Summary counts too large on print version

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantvis#44]
When printing the cards that contain the summary amounts take up one page. Unlikely that we want this.

This is behaviour being inherited from the 360 Design system so we will need to override it.

**Comment by mariongalley** [comment]
Let's tackle alongside #35

**Comment by michaelwood** [comment]
This is fixed on the home page but not after making a dataset selection

**Comment by mariongalley** [comment]
Looks OK to me now

**Comment by michaelwood** [comment]
Yep this was improved, think any further changes can be in a new issue.
