### ISSUE TITLE
Design for Insights to Grantnav button(?)

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantvis#45]
Some kind of banner or button or something looks to be needed for the new Insights to GrantNav linking

**Comment by Bjwebb** [comment]
How does this look?

![Screenshot from 2022-01-25 15-44-01](https://user-images.githubusercontent.com/634/151009464-49a7f1f5-66d4-41d6-8036-571f14b35a23.png)

**Comment by michaelwood** [comment]
@mariongalley Have you folks got any preference for this?

**Comment by mariongalley** [comment]
I think having it be a reasonably prominent button makes sense. This one is well situated but looks a bit plain, could it be GrantNav orange? @robredpath Do we want to tie this in with the design of the GrantNav & Insights buttons on the Org page?

**Comment by michaelwood** [comment]
Make this match the dashboard e.g. http://dashboard.360dashboard.vs.mythic-beasts.com/publisher/360G-ABCT (until we have jazzy buttons)
