### ISSUE TITLE
Write saltstack deployment/mgmt scripts

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantvis#5]

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Write saltstack deployment/mgmt scripts](https://trello.com/c/eBp5DkNA/22-write-saltstack-deployment-mgmt-scripts)

**Comment by Bjwebb** [comment]
There's a PR for this now: https://github.com/ThreeSixtyGiving/saltstack-deploy/pull/21
