### ISSUE TITLE
Award date Axis labelling

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#51]
Award date doesn't have very clear labelling on either axis: 
![image](https://user-images.githubusercontent.com/82958988/151334874-e371f818-17dd-4f20-859c-a67ca811dbfb.png)

Looks to me like the "number of grants" info could do with being repeated more specifically as a label on the y axis, and the x axis needs to explicitly state that it's by month, as you can only see that if you hover over a bar currently.

We don't need to put in every month but could try displaying at least a handful dynamically based on the number of years displayed?

**Comment by mariongalley** [comment]
Think this would benefit greatly from the default date range being smaller e.g. 3 or 5 years rather than all time.

**Comment by mariongalley** [comment]
Relates to https://github.com/ThreeSixtyGiving/insights-ng/issues/72

**Comment by codemacabre** [comment]
@mariongalley The current (new) implementation of this is to only display years by default (and only the first instance of each year, i.e. for the January data point). Months and years are displayed when the date range is narrowed to within a year.

This means the $x$-axis labelling can be quite sparse at times (e.g. when the date range is filtered to 2 or three years). No changes have been made to the $y$-axis.

+ Are you happy with the current $x$-axis implementation?
+ Do you still want the $y$-axis to be labelled 'number of grants'?

**Comment by mariongalley** [comment]
@codemacabre
- Given the sparseness of the x axis labels, could it switch to showing months and years when the range is < 5 years rather than < 1 year?
- For the y axis, it looks OK to me at the moment, although I feel like it might be better practice to label both axes clearly. What do you think?

**Comment by codemacabre** [comment]
@mariongalley

+ 5 years appears a bit cluttered:
  ![image](https://github.com/ThreeSixtyGiving/360insights/assets/49149591/981d4537-3801-4a41-894a-b57ac7dc123a)
  4 years seems like the best option between sparsity and crampedness:
  ![image](https://github.com/ThreeSixtyGiving/360insights/assets/49149591/6d39d517-e6db-4cb8-b6e3-ac4b90c1a55e)

+ I think the chart title and tooltips cover the information well enough without needing axis labels, but it's a stylistic choice.

**Comment by mariongalley** [comment]
@codemacabre Thanks for this! Happy to go with 4 years than - and leave the axis labelling
