### ISSUE TITLE
No Dataset selected -  just go back to homepage?

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#53]
It seems counter intuitive to me that when you clear your selection it displays what looks like an error saying no dataset was selected instead of just taking you back to the Select a Dataset/Homepage/default view.

![image](https://user-images.githubusercontent.com/82958988/151350751-f1fa85bb-15de-43e5-b5df-8a45e46c2b3a.png)

E.g. in GrantNav if you clear your filters it takes you back to the All Results page. I think this is fairly standard behaviour.

Can we do that instead?

**Comment by michaelwood** [comment]
Note that due to the "debounce" (i.e. deliberate delay) on applying filters there is a short delay in this triggering so we keep the "no filters" message in the application whilst it redirects to the home page. PR #83
