### ISSUE TITLE
Choropleth - difficult to use

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#54]
I'm not sure what I expected from the Chloropleth map, but I didn't find it obvious to work out what it does/how to get more from it.

I think that a few things could help with this:
1) It needs a more clear title/explanation of what it's showing as "Heat Map" doesn't tell me what of. Perhaps "Regional Distribution by number of Grants" or similar
2) It needs some instructions on how you can see something different e.g. "Zoom into a Country/Region to view Local Authority-level data"
3) The Zoom needs to switch from Region to LA sooner, because at the moment you have to zoom really far into a region for it to switch - I would never naturally zoom until I could only see one colour across the entire screen. Currently you have to zoom in until you can't see any of the neighbouring regions, but as a result you can't get a good view of the whole region broken down by LA. I think as soon as you have zoomed in enough to see the whole region and only partially the neighbouring regions then you can assume the user wants to view that region broken down by LA.
4) It's too zoomed in by default which makes it less meaningful as you can only see 6/7 regions at once giving you minimal data. Plus I don't think NI/Scotland/the South West will be too happy about being chopped off 😅

**Comment by mariongalley** [comment]
Ask from the team: Can we have a colour code for the heat map

I suspect the colours are probably relative so that Red = most and Yellow = least, but the cutoff for when one colour changes to the next varies based on the absolute numbers of grants for that area. Is that right?

If so, I still think we should have a key showing the shades of Yellow>Orange>Red marked Least > Most.

**Comment by michaelwood** [comment]
Yep 1-3 sound good.

> 4. It's too zoomed in by default which makes it less meaningful as you can only see 6/7 regions at once giving you minimal data. Plus I don't think NI/Scotland/the South West will be too happy about being chopped off sweat_smile

Yeah I spent a while trying to think of how to do this. Basically the UK is the worst shape for viewing in landscape! The only thing is if we zoom out to have the whole of the UK visible the user will need to zoom in more times before they can see towns/recognisable things, bringing the switch over to LA data earlier in the zoom will help with the lack of needing to zoom in though. 

> Ask from the team: Can we have a colour code for the heat map
> 
> I suspect the colours are probably relative so that Red = most and Yellow = least, but the cutoff for when one colour changes to the next varies based on the absolute numbers of grants for that area. Is that right?
> 

Yes you're right they're not fixed bands, to get a distribution of colours it's relative and determined by `grants value / max number of grants in the dataset`.

I think it should be possible to describe this in a key. We should probably make it clear which dataset the key is describing because it will change.

**Comment by mariongalley** [comment]
> Basically the UK is the worst shape for viewing in landscape! 

😢 

> The only thing is if we zoom out to have the whole of the UK visible the user will need to zoom in more times before they can see towns/recognisable things, bringing the switch over to LA data earlier in the zoom will help with the lack of needing to zoom in though.

I think that sounds like a good solution then: have it more zoomed out by default, show the LAs sooner, keep Scotland happy.

**Comment by robredpath** [comment]
Fundamentally, this is a different interaction than I imagined: I expected to be able to click on a region, and have that act as a filter: if I click on East of England, I'd have expected three things:
* The map to show the LAs in the East of England, and nothing else - each of which is clickable to filter further
* All of the graphs to update to only show results from that region
* A way of removing that filter to appear

I understand that's challenging and what's there is good - but I wanted to note this for the future (or, if it's actually straightforward, do it!) 

EDIT: I just worked out that you can click on the name when it appears!

**Comment by Bjwebb** [comment]
I think the work that is prerequisite for live has been done on this. https://github.com/ThreeSixtyGiving/insights-ng/pull/78

**Comment by mariongalley** [comment]
I'm happy to close this. @robredpath is there anything you raised here that you'd like to retain or move to a new issue?
