### ISSUE TITLE
Use accountancy commas for all numbers > 999

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantvis#55]
![image](https://user-images.githubusercontent.com/82958988/151354896-8eeb1a9d-ea93-48ff-a00c-0c6e216f9baa.png)

They're used in the copy at the bottom but not on the bar chart labels for e.g.

**Comment by mariongalley** [comment]
Also please can you capitalise Billion in the summary stats

![image](https://user-images.githubusercontent.com/82958988/151581711-f0c8f1c0-fa9d-4bf7-880b-34ca8958c56d.png)

**Comment by mariongalley** [comment]
Oh and also I've had an ask for change the K to full numbers. That would make it consistent with GrantNav but not with the Quality Dashboard iirc?

![image](https://user-images.githubusercontent.com/82958988/151586074-04f93117-e027-43d2-96c1-187552474a33.png)

**Comment by mariongalley** [comment]
Can we add accountancy commas and also switch billion to be bn and inline like the Ks are.

We can make it consistent with both GrantNav and the Dashboard if we *do* use Ks and bns to shorten £ amounts but don't use Ks to shorten grant and recipient counts. Let's go for that.

**Comment by KDuerden** [comment]
There is a brand/design consistency issue coming up with numbers - recently resolved query about how numbers show in [Dashboard here](https://github.com/ThreeSixtyGiving/registry/issues/95), so flagging here in case it has an impact on what choices get made for Insights.

I personally think the approx k values are less useful for grant recipient counts, especially when viewing a filtered search, as there is no specific count of these given anywhere else.

**Comment by mariongalley** [comment]
Before we switch from a rounded count to the exact number, we should address the issue with [deduplicating recipients and ensure the logic is consistent](https://opendataservices.plan.io/issues/34722) between GrantNav, Insights and the Quality Dashboard.

**Comment by codemacabre** [comment]
@mariongalley This appears to be two separate issues:

1. Using accountancy commas consistently
2. Using numeric abbreviations consistently

The accountancy comma part of this issue seems to be ready to work on, but a style doesn't appear to have been confirmed for numeric abbreviations. As these issues use different libraries, it'd be best to have a separate issue for the numeric abbreviations issue; please could you create one and confirm if the style has been finalised?

**Comment by mariongalley** [comment]
@codemacabre Agree those seem to be the 2 issues. Happy to create a separate ticket for the latter.

I think the rules have been agreed and they are:
-  Switch billion to be bn and inline like the Ks are
- Use approx values for Grant and Amount counts but never for Recipient counts

However, there was a blocker to doing this because [the Recipient counts don't match across the tools](https://opendataservices.plan.io/issues/34722), which @michaelwood was looking into. They're still different in GrantNav and the Quality Dashboard, but I'd expect Insights to match GrantNav now that they use the same dedup rules for counting recipients. Is it possible to confirm whether that would be the case? If so, this can also be fixed now.

**Comment by mariongalley** [comment]
See new issue #164
