### ISSUE TITLE
Persistence of file links from current to new Insights

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantvis#61]
A number of publishing organisations link to their 360Insights files on their websites.
For example: https://insights.threesixtygiving.org/file/a003W000001MPfwQAG

With the switch to new style Insights, will these links still work? What options are available if these aren't accessible anymore, could redirects be put in place or do the affected users need to be informed of the changes?

**Comment by michaelwood** [comment]
I think we could make a backward compatible redirect, the main issue is that new insights currently does not (frontend wise) have a file or publisher concept. 

So we could do `a003W000001MPfwQAG`  -> look up the funder -> 

GB-CHC-326340
GB-CHC-210291
GB-CHC-1087167
GB-CHC-1091658
GB-CHC-312749

Selects: http://insights-ng.insightsng.vs.mythic-beasts.com/data?funders=GB-CHC-326340&funders=GB-CHC-210291&funders=GB-CHC-1087167&funders=GB-CHC-1091658&funders=GB-CHC-312749

**Comment by KDuerden** [comment]
We're already planning to finding all the occurrences of GrantNav or Insights links on external websites, so it maybe we can do comms/engagement to get people to make updates.

**Comment by mariongalley** [comment]
Agreed that we won't aim to make the file-based links backwards compatible. We will instead run a small campaign targeting publishers who we know share their Insights page on their website.

@michaelwood Please can we set up a couple of redirects manually from old file link to new publisher link for publishers we identify as having Insights links on their websites?

**Comment by michaelwood** [comment]
Now deployed and ready for testing (please note new url for testing in planio 32799

**Comment by mariongalley** [comment]
That's brilliant, thanks @michaelwood . I've tested this for AB, Esmee and Mercer's, who are the 3 we know have links to old Insights on their website. And these all work. FYI @KDuerden (Also omg it was so much quicker in new Insights!)
