### ISSUE TITLE
Data with Region or Country beneficiary location displays inconsistent results between chart and map

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantvis#62]
CAF provides a complete set of recipient geocodes at Ward level and beneficiary location geocodes at Region and Country level. 

http://insights-ng.insightsng.vs.mythic-beasts.com/data?funders=GB-CHC-268369

The chart defaults to showing only a few results mapped against regions.

![image](https://user-images.githubusercontent.com/20462640/151515583-cf21b2ba-86d7-430d-a665-c46177cc03ad.png)

If you then select one of the regions as a filter, the other results come up in the list, but the naming is unclear and only those which were listed in the original chart can be selected. The others do not respond to being selected.

![image](https://user-images.githubusercontent.com/20462640/151516237-6d83d7a4-9e1d-4227-b298-eadc4448201f.png)

Elsewhere the map and the chart to breakdown the location source are inconsistent.

![image](https://user-images.githubusercontent.com/20462640/151516440-c19d046a-eefe-4fc2-95db-488d2a059a1f.png)

**Comment by michaelwood** [comment]
For prerequisite-for-live make sure that the multiple "England -" are properly allocated to England rather than duplicated.

**Comment by michaelwood** [comment]
Related to #91
