### ISSUE TITLE
Source of location information chart - doesn't function as filter

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantvis#63]
Source of location information chart look like the other charts which work as filters.

The hand icon appears if you hover over one of the values but there is no response if you try to select.

![image](https://user-images.githubusercontent.com/20462640/151518452-0c5cf12a-ace9-4936-b864-cb5d12c92f01.png)

If this is intended to work as a filter, the functionality needs to be fixed.
If it isn't intended to work as a filter, a note or visual que should help users understand that it is just a chart, not a filter too.

**Comment by michaelwood** [comment]
prerequisite for live : Remove clickable status of the graph bars
