### ISSUE TITLE
Use consistent and clear names for organisation types

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantvis#66]
The organisation type chart has a mixture of full names, but also dash separated values and org ID prefixes.

http://insights-ng.insightsng.vs.mythic-beasts.com/data?area=W92000004&area=N92000002&area=E12000001&area=S92000003

The differences between 'Registered Company' and company-limited-by-guarantee are not clear and potentially confusing.

Registered Charity (Scotland) and scottish-charitable-incorporated-organisation appear as separate values but the latter is a type of the former.

**Comment by mariongalley** [comment]
This problem exists upstream - values are from the datastore.

**Comment by mariongalley** [comment]
Had more feedback about this so adding to project board to prioritise
> The recipient labels on Insights are a bit messed up and it is hard to understand all the company labels like registered-company separate from Registered Company. It would be good to be able to select CICs and it would be good to be able to select all UK companies and all UK Charities rather than spending ages picking out different nations

![image](https://github.com/ThreeSixtyGiving/360insights/assets/82958988/1ffe8848-746f-4cf6-9da7-bab624944cb2)

**Comment by mariongalley** [comment]
This issue is fixed in the new iteration of Insights PR #208
