### ISSUE TITLE
Suggestion - Add Award Date filter to homepage

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantvis#72]
There are grants going back to 1990s in the dataset, so allowing users to filter by date will help them get relevant results quickly.

It would also help reduce the time needed for large funders or areas results to load - eg currently if you select England from the countries the file doesn't load the results.

The date filter is the fourth filter on the results page so not that prominent for users.

**Comment by mariongalley** [comment]
Add to this: I think it should default to recent data only once this filter is available e.g. last 5 years only (and perhaps only going up to the end of the last complete financial year, as current year data is known to be very patchy)

**Comment by codemacabre** [comment]
> I think it should default to recent data only once this filter is available e.g. last 5 years only (and perhaps only going up to the end of the last complete financial year, as current year data is known to be very patchy)

@mariongalley Do you still want this default shorter date range to be implemented?

**Comment by mariongalley** [comment]
@codemacabre For now no - we've decided it's more important for Insights and GrantNav to show the same headline stats for the whole dataset so people can understand they're exploring the same data in both tools

**Comment by mariongalley** [comment]
However I still can't get any searches to load when filtered by date @codemacabre - I know this has been like this for a while but I'd consider this a high priority bug as it affects the core functioning of the tool. Would you be able to take a look at why that is?

**Comment by codemacabre** [comment]
> However I still can't get any searches to load when filtered by date @codemacabre - I know this has been like this for a while but I'd consider this a high priority bug as it affects the core functioning of the tool. Would you be able to take a look at why that is?

Is the issue that it takes a (really) long time to load the page when filtering? It eventually loads after a couple of minutes; I suspect something to do with caching. Or is it something else?

**Comment by mariongalley** [comment]
@codemacabre Yeah that is the issue - it took so long to load that I went and did something else and just came back to it now, so I'm not sure how long it was. Given how quickly people abandon web pages that don't load, it doesn't work for all intents and purposes. If it's a caching issue, it seems to persist 100% of the time in my experience.

**Comment by codemacabre** [comment]
Thanks @mariongalley, we'll look into it.

**Comment by mariongalley** [comment]
This issue is resolved, and the performance is being looked at separately
