### ISSUE TITLE
Don't show mixture of data about other currencies

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantvis#75]
Currently the behaviour is showing some information about grants made in other currencies however this is confusing as it's only visible in certain filters. 

The warning about this issue needs to be made more visible.

**Comment by michaelwood** [comment]
I've tried to make this more explanatory with a list of the other values. I couldn't find anything in the design system that would really allow this, given that we don't know the length of the list (though for now I think it's unlikely that there are other publishers with many currencies).

![Screenshot from 2022-02-08 17-14-34](https://user-images.githubusercontent.com/493697/153039944-13f3ed02-7fc0-44d6-8935-3d46e6780bde.png)
@mariongalley @KDuerden

**Comment by KDuerden** [comment]
That looks good thank you. For reference, 3 non-GBP currencies is the most a current funder has.

**Comment by michaelwood** [comment]
Closing for now
