### ISSUE TITLE
Explain why map only shows 1,000 records

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/grantvis#91]
The map currently only shows 1,000 records, I think because of load on the db plus performance of the map itself. It would be good to be clear to users why they are seeing a maximum of 1,000 records. 

A related point is that I'm not sure how the 1,000 rows are chosen. There's a possibility that they have a geographic bias - eg if one funder's grants are first in the list and those are the 1,000 rows picked, then they might not represent the overall distribution of grants.

**Comment by michaelwood** [comment]
I'm seeing a LIMIT 1000, OFFSET 0 in the sql query that is produced by graphene/sqlalchemy which a little research tells me is something to do with pagination of results, as we could return 100,000s of items and a map not being pagination friendly I think we need to look at aggregate data instead.

**Comment by mariongalley** [comment]
@michaelwood Does using aggregate data = switching to a choropleth?

**Comment by michaelwood** [comment]
> @michaelwood Does using aggregate data = switching to a choropleth?

Yes I think so, I'm just trying to make sure that the data on both the homepage and a data page is compatible with creating a choropleth

**Comment by mariongalley** [comment]
@michaelwood That sounds good. Do you think you'll have something for us to test and make a call about switching over to the live URL within the next couple of hours?

**Comment by michaelwood** [comment]
@mariongalley should do! I'm just ironing out some of the issues now

**Comment by mariongalley** [comment]
This has been resolved by switching to a choropleth
